# Generated by Django 4.2 on 2023-04-19 18:50

import Account_Modul.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Modul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modile',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=Account_Modul.models.upload_image_path, verbose_name='تصویر آواتار'),
        ),
    ]
