# Generated by Django 4.2 on 2023-04-22 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Modul', '0003_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify_code',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
