# Generated by Django 4.2 on 2023-04-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Modul', '0004_alter_verify_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='درباره شخص'),
        ),
    ]
