# Generated by Django 4.2 on 2023-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Modul', '0005_user_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facbook_account',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='اکانت فیسبوک'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_account',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='اکانت اینستاگرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_account',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='اکانت لینکدین'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_account',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='اکانت توییتر'),
        ),
    ]
