# Generated by Django 4.2 on 2023-05-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Modul', '0006_user_facbook_account_user_instagram_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
