# Generated by Django 4.2 on 2023-07-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Modul', '0007_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='postalـcode',
            field=models.TextField(blank=True, null=True, verbose_name='کد پستی'),
        ),
    ]
