# Generated by Django 4.2 on 2023-07-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Modul', '0008_user_phone_user_postalـcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postalـcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
    ]
