# Generated by Django 4.2 on 2023-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Modul', '0002_alter_orderdetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده/نشده'),
        ),
    ]
