# Generated by Django 4.2 on 2023-07-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Modul', '0004_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_invoice',
            field=models.IntegerField(blank=True, null=True, verbose_name='جمع فاکتور'),
        ),
    ]
