# Generated by Django 4.2 on 2023-07-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Modul', '0005_order_total_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد رهگیری'),
        ),
    ]
