# Generated by Django 4.2 on 2023-07-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Modul', '0006_order_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبایل'),
        ),
        migrations.AddField(
            model_name='order',
            name='postalـcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
    ]
