# Generated by Django 4.2 on 2023-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_productvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='نعداد بازدید'),
        ),
    ]
