# Generated by Django 4.2 on 2023-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='نعداد بازدید'),
        ),
    ]
