# Generated by Django 4.2 on 2023-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('sitr_url', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس سایت')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن سایت')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس سایت')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل سایت')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت سایت')),
                ('about_us_text', models.TextField(verbose_name='متن درباره سایت')),
                ('site_logo', models.ImageField(upload_to='Site_Setting/', verbose_name='لوگو سابت')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
