# Generated by Django 4.2 on 2023-04-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Modul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_setting',
            name='address',
            field=models.CharField(max_length=300, verbose_name='آدرس '),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل '),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس '),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن '),
        ),
        migrations.CreateModel(
            name='Social_Network_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network_name', models.CharField(max_length=200, verbose_name='اسم سوشیال مدیا')),
                ('social_network_url', models.CharField(max_length=200, verbose_name='لینک سوشیال مدیا')),
                ('site_seting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Site_Modul.site_setting')),
            ],
        ),
    ]
