# Generated by Django 4.2 on 2023-04-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Modul', '0003_footerlinkbox_alter_social_network_site_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url', models.CharField(max_length=300, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=400, verbose_name='عنوان لینک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='Slider/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='footer_link_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='footer_link_box', to='Site_Modul.footerlinkbox', verbose_name='دسته بندی'),
        ),
    ]
