# Generated by Django 4.2 on 2023-04-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Modul', '0005_slider_is_avtive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='is_avtive',
            new_name='is_active',
        ),
    ]
