# Generated by Django 4.2 on 2023-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Modul', '0006_rename_is_avtive_slider_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=400, verbose_name='نام و نام خانوادگی کارمند')),
                ('employee_image', models.ImageField(upload_to='Employees/', verbose_name='تصویر کارمند')),
                ('employee_position', models.CharField(max_length=200, verbose_name='سِمَت کارمند')),
                ('employee_alredy', models.BooleanField(default=True, verbose_name='آیا مشغول به کار است')),
                ('employee_recruitment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کارمند شرکت',
                'verbose_name_plural': 'کارمندان',
            },
        ),
    ]
