# Generated by Django 4.2 on 2023-06-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Modul', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='لینک تبلیغ')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر تبلیغ')),
                ('is_active', models.BooleanField(verbose_name='فعال یا غیر فعال')),
                ('position', models.CharField(choices=[('product_list', 'لیست محصولات'), ('product_detail', 'جزیات محصولات'), ('contact_us', 'ارتباط با ما')], max_length=200)),
            ],
            options={
                'verbose_name': 'تلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
    ]
