# Generated by Django 4.2 on 2023-06-05 21:25

import Site_Modul.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Modul', '0008_site_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_banner',
            name='image',
            field=models.ImageField(upload_to=Site_Modul.models.upload_image_path, verbose_name='تصویر تبلیغ'),
        ),
    ]
