# Generated by Django 4.2 on 2023-06-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Modul', '0009_alter_site_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_banner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
