# Generated by Django 4.2 on 2023-06-25 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Article_Module', '0008_alter_articlecomment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='آپی کاربر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Article_Module.article', verbose_name='نام محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید مقاله',
                'verbose_name_plural': 'بازدید مقاله',
            },
        ),
    ]
