# Generated by Django 4.2 on 2023-06-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Module', '0009_articlevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
